### ISSUE TITLE
Running python 3.7.4 gives callback error on macOS 10.13.6

### ISSUE THREAD

**Issue by jgaeddert** [fbieberly/ORBCOMM-receiver#3]
```
$ python3 realtime_receiver.py 






Found Rafael Micro R820T tuner

Satellites overhead: 
orbcomm fm117       : 22.6 degrees elevation
Receiving from: orbcomm fm117
Satellite frequencies: [137460000.0, 137712500.0]
Recording samples.
Create multiprocessing queue
Creating multiprocessing process
Frequency offset: -96.28180039138942
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python3.7/site-packages/rtlsdr/rtlsdr.py", line 628, in _bytes_converter_callback
    self._callback_bytes(values, context)
  File "/usr/local/lib/python3.7/site-packages/rtlsdr/rtlsdr.py", line 675, in _samples_converter_callback
    self._callback_samples(iq, context)
  File "realtime_receiver.py", line 115, in rtlsdr_callback
    if queue.qsize() > 30:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/usr/local/lib/python3.7/site-packages/rtlsdr/rtlsdr.py", line 628, in _bytes_converter_callback
    self._callback_bytes(values, context)
  File "/usr/local/lib/python3.7/site-packages/rtlsdr/rtlsdr.py", line 675, in _samples_converter_callback
    self._callback_samples(iq, context)
  File "realtime_receiver.py", line 115, in rtlsdr_callback
    if queue.qsize() > 30:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
...
(many, many more of the same)
```

**Comment by jgaeddert** [comment]
I should note this is on the `dev` branch

**Comment by fbieberly** [comment]
This one will be a little hard for me to troubleshoot since I don't have a macOS computer to test on. 

I made a change in the code to remove the queue.qsize() call and replaced it with queue.empty()/queue.full() calls. I'm not confident that will solve the problem. But if you could try that out, that'd be great.

**Comment by jgaeddert** [comment]
Didn't seem to make any difference. I'm not an expert on python threads. This doesn't seem like a problem on your end but maybe Python's implementation. What version of Python are you running?

**Comment by fbieberly** [comment]
You are right. This is a Python/Mac OS thing. It says in the Python docs (for all versions) that queue.qsize() throws a NotImplementedError: https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.Queue.qsize
But, it only mentions it for that method, so I hoped the empty/full methods would be fine. You still get a NotImplementedError? Could you copy/paste the error traceback again?

**Comment by jgaeddert** [comment]
```
$ python3 realtime_receiver.py 
Found Rafael Micro R820T tuner
Time until next satellite  (orbcomm fm117) visible: 3 minutes
Time until next satellite  (orbcomm fm117) visible: 2 minutes

Satellites overhead: 
orbcomm fm117       : 5.0 degrees elevation
Receiving from: orbcomm fm117
Satellite frequencies: [137460000.0, 137712500.0]
Recording samples.
Create multiprocessing queue
Creating multiprocessing process
Frequency offset: -126.81017612524461
Ending async RTLSDR processing
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 398, in _send_bytes
    self._send(buf)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
...
(repeats for a few hundred more lines)
...
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Program exited.
```

**Comment by fbieberly** [comment]
I'm not sure I can fix this without a mac to test on. So, I'm going to shelve this issue. If you discover a fix I'll gladly accept a pull request.

**Comment by zuzalite** [comment]
Raspberry Pi 3 B+  :-(

Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Time until next satellite  (orbcomm fm114) visible: 2 minutes

Satellites overhead:
orbcomm fm114       : 5.0 degrees elevation
Receiving from: orbcomm fm114
Satellite frequencies: [137287500.0, 137737500.0]
Traceback (most recent call last):
  File "realtime_receiver.py", line 322, in <module>
    decoder = RealtimeDecoder(sat_center_frequency, center_freq=center_freq, sample_rate=sample_rate)
  File "/home/pi/ORBCOMM-receiver/realtime_decoder.py", line 27, in __init__
    self.init_default_values()
  File "/home/pi/ORBCOMM-receiver/realtime_decoder.py", line 82, in init_default_values
    self.lpf_fir_taps = firwin(self.lpf_order, self.lpf_filter_freq, fs=self.sample_rate)
TypeError: firwin() got an unexpected keyword argument 'fs'

**Comment by fbieberly** [comment]
Hi zuzalite, 
You probably have an old version of scipy. It needs to be version 1.0.0 or higher. I'll update the readme dependencies. Thanks for reporting.
